### ISSUE TITLE
Can't install manually

### ISSUE THREAD

**Issue by rdhrkns** [fatfishdigital/Navigation#2]
Tried to install manually, but the plugin does not appear in the list...

**Comment by fatfishdigital** [comment]
@rdhrkns can you please explain the process how you did it ? it will help to troubleshoot

**Comment by rdhrkns** [comment]
Hi,

I downloaded the repo from here, extracted the zip file locally and uploaded the folder 'navigation' and it's contents content to a folder named 'flatfish' in the Craft vendor folder location. 
As I do not have command line access to the server I'm guessing it has to do with telling composer to update itself correct ?

**Comment by fatfishdigital** [comment]
@rdhrkns you can install directly from craft store now, it's on composer public store now. you do not have to generate fatfish folder in order to do it, if you have command line access then you can just create plugin folder in root of the craft site and adjust composer.json file according to it. For now you should be able to install it directly from craft store.

**Comment by rdhrkns** [comment]
Hello,

Under which search query can I find it in the store.  It is not showing  under Fatfish, navigation, nav, Craft or any combination of such ?

Unfortunatley I have no SSH acces to the shares hosting setup.

-R

**Comment by fatfishdigital** [comment]
@rdhrkns search with craft-navigation.
